version: '3.5'

services:
  postgres:
    image: "postgres"
    env_file:
      - database.env
    container_name: "my_postgres"
    ports:
      - "1122:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    restart: always

  pgadmin:
    image: "dpage/pgadmin4"
    volumes:
      - pgadmin:/home/pgadmin/.pgadmin
    container_name: "my_postgres_admin"
    ports:
      - "5050:80"
    env_file:
      - database.env
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: